apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-app
  template:
    metadata:
      labels:
        app: brain-app
    spec:
      containers:
      - name: brain-app
        image: 140324736450.dkr.ecr.us-west-2.amazonaws.com/brain-tasks-repo:latest
        ports:
        - containerPort: 80
